# Generated by Django 3.2.6 on 2021-09-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
