# Generated by Django 3.2.6 on 2021-09-19 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_tries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tries',
            options={'verbose_name_plural': 'Tries'},
        ),
        migrations.AddField(
            model_name='question',
            name='addedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=500),
        ),
    ]
