# Generated by Django 3.2.6 on 2021-09-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210919_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SponsoredTries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tries', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.user')),
            ],
            options={
                'verbose_name_plural': 'Tries',
            },
        ),
        migrations.CreateModel(
            name='SponsoredScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPoints', models.IntegerField(default=0)),
                ('timeTaken', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.user')),
            ],
            options={
                'ordering': ['-totalPoints', 'timeTaken'],
            },
        ),
        migrations.CreateModel(
            name='SponsoredQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=64)),
                ('timePeriod', models.IntegerField(default=60)),
                ('scoreboard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.sponsoredscore')),
                ('tryBoard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.sponsoredtries')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='practiceBranch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='quiz.practicequestions'),
        ),
        migrations.AddField(
            model_name='question',
            name='sponsorship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='quiz.sponsoredquestions'),
        ),
    ]
