# Generated by Django 3.2.6 on 2021-09-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210927_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tries', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Sponsored Tries',
            },
        ),
        migrations.CreateModel(
            name='SponsoredScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPoints', models.IntegerField(default=0)),
                ('timeTaken', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-totalPoints', 'timeTaken'],
            },
        ),
        migrations.RemoveField(
            model_name='sponsoredtries',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='practicequestions',
            options={'verbose_name_plural': 'Practice Branch'},
        ),
        migrations.AlterModelOptions(
            name='sponsoredquestions',
            options={'verbose_name_plural': 'Sponsored Details'},
        ),
        migrations.RemoveField(
            model_name='sponsoredquestions',
            name='scoreboard',
        ),
        migrations.RemoveField(
            model_name='sponsoredquestions',
            name='tryBoard',
        ),
        migrations.DeleteModel(
            name='SponsoredScore',
        ),
        migrations.DeleteModel(
            name='SponsoredTries',
        ),
        migrations.AddField(
            model_name='sponsoredscoreboard',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.sponsoredquestions'),
        ),
        migrations.AddField(
            model_name='sponsoredscoreboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.user'),
        ),
        migrations.AddField(
            model_name='sponsoredattempts',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.sponsoredquestions'),
        ),
        migrations.AddField(
            model_name='sponsoredattempts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.user'),
        ),
    ]
