# Generated by Django 3.2.6 on 2021-10-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20211008_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsoredscoreboard',
            options={'ordering': ['-totalPoints']},
        ),
        migrations.RemoveField(
            model_name='sponsoredscoreboard',
            name='timeTaken',
        ),
        migrations.AddField(
            model_name='sponsoredquestions',
            name='examCode',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sponsoredquestions',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sponsoredscoreboard',
            name='branch',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sponsoredscoreboard',
            name='section',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sponsoredscoreboard',
            name='year',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='sponsoredquestions',
            name='branch',
            field=models.CharField(max_length=10, null=''),
        ),
        migrations.AlterField(
            model_name='sponsoredquestions',
            name='name',
            field=models.CharField(max_length=64, null=''),
        ),
    ]
