# Generated by Django 3.2.6 on 2021-10-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20211008_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredquestions',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
    ]
