# Generated by Django 3.2.6 on 2021-10-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_sponsoredquestions_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='practiceBranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quiz.practicequestions'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sponsorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quiz.sponsoredquestions'),
        ),
    ]
