# Generated by Django 3.2.6 on 2021-10-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20211008_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoredattempts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.user'),
        ),
    ]
